### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by andrzejnovak** [not-lum/imgcat#2]
Hi, I tried installing this, but I seem to hit the following error:

```
/home/anovak/.nimble/pkgs/flippy-0.4.5/flippy.nim(292, 58) Error: undeclared identifier: 'Rect'
```

Installing flippy by itself seems to work fine.

**Comment by Flammable-Duck** [comment]
I have the same problem.

**Comment by ykerit** [comment]
I have same problem

**Comment by hktonylee** [comment]
I have the same problem as well

**Comment by not-lum** [comment]
Fixed
